/* Auto-generated by genmsg_cpp for file /home/matt/AU-UAV-ROS/AU_UAV_ROS/msg/TelemetryUpdate.msg */
#ifndef AU_UAV_ROS_MESSAGE_TELEMETRYUPDATE_H
#define AU_UAV_ROS_MESSAGE_TELEMETRYUPDATE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace AU_UAV_ROS
{
template <class ContainerAllocator>
struct TelemetryUpdate_ : public ros::Message
{
  typedef TelemetryUpdate_<ContainerAllocator> Type;

  TelemetryUpdate_()
  : telemetryHeader()
  , update()
  {
  }

  TelemetryUpdate_(const ContainerAllocator& _alloc)
  : telemetryHeader(_alloc)
  , update(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _telemetryHeader_type;
   ::std_msgs::Header_<ContainerAllocator>  telemetryHeader;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _update_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  update;


private:
  static const char* __s_getDataType_() { return "AU_UAV_ROS/TelemetryUpdate"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "72b8d75e83b2990685728c91cbd65231"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header telemetryHeader\n\
string update\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, telemetryHeader);
    ros::serialization::serialize(stream, update);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, telemetryHeader);
    ros::serialization::deserialize(stream, update);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(telemetryHeader);
    size += ros::serialization::serializationLength(update);
    return size;
  }

  typedef boost::shared_ptr< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator>  const> ConstPtr;
}; // struct TelemetryUpdate
typedef  ::AU_UAV_ROS::TelemetryUpdate_<std::allocator<void> > TelemetryUpdate;

typedef boost::shared_ptr< ::AU_UAV_ROS::TelemetryUpdate> TelemetryUpdatePtr;
typedef boost::shared_ptr< ::AU_UAV_ROS::TelemetryUpdate const> TelemetryUpdateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace AU_UAV_ROS

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "72b8d75e83b2990685728c91cbd65231";
  }

  static const char* value(const  ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x72b8d75e83b29906ULL;
  static const uint64_t static_value2 = 0x85728c91cbd65231ULL;
};

template<class ContainerAllocator>
struct DataType< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "AU_UAV_ROS/TelemetryUpdate";
  }

  static const char* value(const  ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header telemetryHeader\n\
string update\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.telemetryHeader);
    stream.next(m.update);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TelemetryUpdate_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::AU_UAV_ROS::TelemetryUpdate_<ContainerAllocator> & v) 
  {
    s << indent << "telemetryHeader: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.telemetryHeader);
    s << indent << "update: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.update);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AU_UAV_ROS_MESSAGE_TELEMETRYUPDATE_H

