(cl:defpackage AU_UAV_ROS-srv
  (:use )
  (:export
   "CREATESIMULATEDPLANE"
   "<CREATESIMULATEDPLANE-REQUEST>"
   "CREATESIMULATEDPLANE-REQUEST"
   "<CREATESIMULATEDPLANE-RESPONSE>"
   "CREATESIMULATEDPLANE-RESPONSE"
   "REQUESTPLANEID"
   "<REQUESTPLANEID-REQUEST>"
   "REQUESTPLANEID-REQUEST"
   "<REQUESTPLANEID-RESPONSE>"
   "REQUESTPLANEID-RESPONSE"
   "GOTOWAYPOINT"
   "<GOTOWAYPOINT-REQUEST>"
   "GOTOWAYPOINT-REQUEST"
   "<GOTOWAYPOINT-RESPONSE>"
   "GOTOWAYPOINT-RESPONSE"
  ))

